apiVersion: v1
kind: Pod
metadata:
  name: pod-placeholder
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node-role.kubernetes.io/node
                operator: In
                values:
                  - kubemark-node
